### ISSUE TITLE
dotnet publish -c Release does not work with Dotnet SDK 3.0 Pre

### ISSUE THREAD

**Issue by juspky** [signumsoftware/framework#396]
Normal build works fine.

Dotnet publish causes problems:

Extensions\Extensions.cs(405,76): error CS8634: Der Typ "T?" kann nicht als Typparameter "R" im generischen Typ oder in der generischen Methode "Extensions.FuncCC<T, R>" verwendet werden. Die NULL-Zulässigkeit des Typarguments "T?" entspricht nicht der class-Einschränkung.

**Comment by olmobrutall** [comment]
this is .net core 3 right? I haven’t tried this framework yet. It’s in beta

**Comment by juspky** [comment]
`<TreatWarningsAsErrors>false</TreatWarningsAsErrors>`
as mentionend in https://github.com/signumsoftware/framework/issues/395 fixes this
